const db = {
  "location": {
    "name": "Dubai",
    "region": "Dubai",
    "country": "United Arab Emirates",
    "lat": 25.25,
    "lon": 55.28,
    "tz_id": "Asia/Dubai",
    "localtime_epoch": 1696090043,
    "localtime": "2023-09-30 20:07"
  },
  "current": {
    "last_updated_epoch": 1696089600,
    "last_updated": "2023-09-30 20:00",
    "temp_c": 36,
    "temp_f": 96.8,
    "is_day": 0,
    "condition": {
      "text": "Clear",
      "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
      "code": 1000
    },
    "wind_mph": 8.1,
    "wind_kph": 13,
    "wind_degree": 360,
    "wind_dir": "N",
    "pressure_mb": 1007,
    "pressure_in": 29.74,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 35,
    "cloud": 0,
    "feelslike_c": 50.2,
    "feelslike_f": 122.4,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1,
    "gust_mph": 12.8,
    "gust_kph": 20.5
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-09-30",
        "date_epoch": 1696032000,
        "day": {
          "maxtemp_c": 33.6,
          "maxtemp_f": 92.5,
          "mintemp_c": 29.6,
          "mintemp_f": 85.4,
          "avgtemp_c": 31.6,
          "avgtemp_f": 88.9,
          "maxwind_mph": 15.4,
          "maxwind_kph": 24.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 59,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 8
        },
        "astro": {
          "sunrise": "06:10 AM",
          "sunset": "06:07 PM",
          "moonrise": "06:54 PM",
          "moonset": "06:56 AM",
          "moon_phase": "Waning Gibbous",
          "moon_illumination": "99",
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1696017600,
            "time": "2023-09-30 00:00",
            "temp_c": 29.8,
            "temp_f": 85.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 100,
            "wind_dir": "E",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 0,
            "feelslike_c": 34.1,
            "feelslike_f": 93.3,
            "windchill_c": 29.8,
            "windchill_f": 85.6,
            "heatindex_c": 34.1,
            "heatindex_f": 93.3,
            "dewpoint_c": 23.2,
            "dewpoint_f": 73.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1696021200,
            "time": "2023-09-30 01:00",
            "temp_c": 30,
            "temp_f": 85.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 0,
            "feelslike_c": 34.2,
            "feelslike_f": 93.6,
            "windchill_c": 30,
            "windchill_f": 85.9,
            "heatindex_c": 34.2,
            "heatindex_f": 93.6,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 15,
            "uv": 1
          },
          {
            "time_epoch": 1696024800,
            "time": "2023-09-30 02:00",
            "temp_c": 29.8,
            "temp_f": 85.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1006,
            "pressure_in": 29.72,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 64,
            "cloud": 0,
            "feelslike_c": 33.4,
            "feelslike_f": 92.1,
            "windchill_c": 29.8,
            "windchill_f": 85.7,
            "heatindex_c": 33.4,
            "heatindex_f": 92.1,
            "dewpoint_c": 22.2,
            "dewpoint_f": 71.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.3,
            "gust_kph": 11.7,
            "uv": 1
          },
          {
            "time_epoch": 1696028400,
            "time": "2023-09-30 03:00",
            "temp_c": 29.6,
            "temp_f": 85.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 53,
            "wind_dir": "NE",
            "pressure_mb": 1007,
            "pressure_in": 29.72,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 0,
            "feelslike_c": 32.9,
            "feelslike_f": 91.3,
            "windchill_c": 29.6,
            "windchill_f": 85.4,
            "heatindex_c": 32.9,
            "heatindex_f": 91.3,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.2,
            "gust_kph": 11.5,
            "uv": 1
          },
          {
            "time_epoch": 1696032000,
            "time": "2023-09-30 04:00",
            "temp_c": 29.7,
            "temp_f": 85.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 29,
            "wind_dir": "NNE",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 2,
            "feelslike_c": 33.1,
            "feelslike_f": 91.5,
            "windchill_c": 29.7,
            "windchill_f": 85.5,
            "heatindex_c": 33.1,
            "heatindex_f": 91.5,
            "dewpoint_c": 21.9,
            "dewpoint_f": 71.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 1
          },
          {
            "time_epoch": 1696035600,
            "time": "2023-09-30 05:00",
            "temp_c": 30.1,
            "temp_f": 86.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 23,
            "wind_dir": "NNE",
            "pressure_mb": 1008,
            "pressure_in": 29.75,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 3,
            "feelslike_c": 34,
            "feelslike_f": 93.2,
            "windchill_c": 30.1,
            "windchill_f": 86.3,
            "heatindex_c": 34,
            "heatindex_f": 93.2,
            "dewpoint_c": 22.4,
            "dewpoint_f": 72.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12,
            "gust_kph": 19.3,
            "uv": 1
          },
          {
            "time_epoch": 1696039200,
            "time": "2023-09-30 06:00",
            "temp_c": 30.3,
            "temp_f": 86.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 32,
            "wind_dir": "NNE",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 2,
            "feelslike_c": 34.4,
            "feelslike_f": 93.9,
            "windchill_c": 30.4,
            "windchill_f": 86.6,
            "heatindex_c": 34.4,
            "heatindex_f": 93.9,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.7,
            "gust_kph": 20.4,
            "uv": 1
          },
          {
            "time_epoch": 1696042800,
            "time": "2023-09-30 07:00",
            "temp_c": 30.7,
            "temp_f": 87.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1009,
            "pressure_in": 29.78,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 0,
            "feelslike_c": 34.9,
            "feelslike_f": 94.8,
            "windchill_c": 30.7,
            "windchill_f": 87.3,
            "heatindex_c": 34.9,
            "heatindex_f": 94.8,
            "dewpoint_c": 22.6,
            "dewpoint_f": 72.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.9,
            "gust_kph": 19.2,
            "uv": 8
          },
          {
            "time_epoch": 1696046400,
            "time": "2023-09-30 08:00",
            "temp_c": 31.4,
            "temp_f": 88.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1009,
            "pressure_in": 29.8,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 2,
            "feelslike_c": 35.7,
            "feelslike_f": 96.3,
            "windchill_c": 31.4,
            "windchill_f": 88.5,
            "heatindex_c": 35.7,
            "heatindex_f": 96.3,
            "dewpoint_c": 22.5,
            "dewpoint_f": 72.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.4,
            "gust_kph": 16.8,
            "uv": 8
          },
          {
            "time_epoch": 1696050000,
            "time": "2023-09-30 09:00",
            "temp_c": 32,
            "temp_f": 89.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 54,
            "cloud": 2,
            "feelslike_c": 35.7,
            "feelslike_f": 96.3,
            "windchill_c": 32,
            "windchill_f": 89.6,
            "heatindex_c": 35.7,
            "heatindex_f": 96.3,
            "dewpoint_c": 21.5,
            "dewpoint_f": 70.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.5,
            "uv": 8
          },
          {
            "time_epoch": 1696053600,
            "time": "2023-09-30 10:00",
            "temp_c": 32.9,
            "temp_f": 91.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 22,
            "wind_dir": "NNE",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 2,
            "feelslike_c": 36,
            "feelslike_f": 96.7,
            "windchill_c": 33,
            "windchill_f": 91.3,
            "heatindex_c": 36,
            "heatindex_f": 96.7,
            "dewpoint_c": 20.1,
            "dewpoint_f": 68.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.4,
            "gust_kph": 7.1,
            "uv": 8
          },
          {
            "time_epoch": 1696057200,
            "time": "2023-09-30 11:00",
            "temp_c": 33.4,
            "temp_f": 92.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 47,
            "cloud": 2,
            "feelslike_c": 36.8,
            "feelslike_f": 98.3,
            "windchill_c": 33.4,
            "windchill_f": 92,
            "heatindex_c": 36.8,
            "heatindex_f": 98.3,
            "dewpoint_c": 20.6,
            "dewpoint_f": 69,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 8
          },
          {
            "time_epoch": 1696060800,
            "time": "2023-09-30 12:00",
            "temp_c": 33.5,
            "temp_f": 92.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 324,
            "wind_dir": "NW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 2,
            "feelslike_c": 37.3,
            "feelslike_f": 99.2,
            "windchill_c": 33.5,
            "windchill_f": 92.3,
            "heatindex_c": 37.3,
            "heatindex_f": 99.2,
            "dewpoint_c": 21.1,
            "dewpoint_f": 69.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.3,
            "uv": 8
          },
          {
            "time_epoch": 1696064400,
            "time": "2023-09-30 13:00",
            "temp_c": 33.4,
            "temp_f": 92.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 313,
            "wind_dir": "NW",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 50,
            "cloud": 2,
            "feelslike_c": 37.5,
            "feelslike_f": 99.4,
            "windchill_c": 33.4,
            "windchill_f": 92,
            "heatindex_c": 37.5,
            "heatindex_f": 99.4,
            "dewpoint_c": 21.4,
            "dewpoint_f": 70.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 8
          },
          {
            "time_epoch": 1696068000,
            "time": "2023-09-30 14:00",
            "temp_c": 33.6,
            "temp_f": 92.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.8,
            "wind_kph": 20.5,
            "wind_degree": 316,
            "wind_dir": "NW",
            "pressure_mb": 1007,
            "pressure_in": 29.75,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 51,
            "cloud": 0,
            "feelslike_c": 38.5,
            "feelslike_f": 101.3,
            "windchill_c": 33.6,
            "windchill_f": 92.5,
            "heatindex_c": 38.5,
            "heatindex_f": 101.3,
            "dewpoint_c": 22.2,
            "dewpoint_f": 72,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 8
          },
          {
            "time_epoch": 1696071600,
            "time": "2023-09-30 15:00",
            "temp_c": 33.3,
            "temp_f": 92,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 15,
            "wind_kph": 24.1,
            "wind_degree": 336,
            "wind_dir": "NNW",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 55,
            "cloud": 1,
            "feelslike_c": 39,
            "feelslike_f": 102.2,
            "windchill_c": 33.3,
            "windchill_f": 92,
            "heatindex_c": 39,
            "heatindex_f": 102.2,
            "dewpoint_c": 23.1,
            "dewpoint_f": 73.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.5,
            "gust_kph": 31.4,
            "uv": 8
          },
          {
            "time_epoch": 1696075200,
            "time": "2023-09-30 16:00",
            "temp_c": 32.9,
            "temp_f": 91.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 15.4,
            "wind_kph": 24.8,
            "wind_degree": 344,
            "wind_dir": "NNW",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 58,
            "cloud": 4,
            "feelslike_c": 38.8,
            "feelslike_f": 101.9,
            "windchill_c": 32.9,
            "windchill_f": 91.3,
            "heatindex_c": 38.8,
            "heatindex_f": 101.9,
            "dewpoint_c": 23.5,
            "dewpoint_f": 74.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 20.4,
            "gust_kph": 32.9,
            "uv": 8
          },
          {
            "time_epoch": 1696078800,
            "time": "2023-09-30 17:00",
            "temp_c": 32.5,
            "temp_f": 90.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 340,
            "wind_dir": "NNW",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 4,
            "feelslike_c": 38.3,
            "feelslike_f": 100.9,
            "windchill_c": 32.5,
            "windchill_f": 90.6,
            "heatindex_c": 38.3,
            "heatindex_f": 100.9,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.3,
            "gust_kph": 29.4,
            "uv": 8
          },
          {
            "time_epoch": 1696082400,
            "time": "2023-09-30 18:00",
            "temp_c": 32.1,
            "temp_f": 89.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1007,
            "pressure_in": 29.75,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 3,
            "feelslike_c": 38.3,
            "feelslike_f": 100.9,
            "windchill_c": 32.1,
            "windchill_f": 89.8,
            "heatindex_c": 38.3,
            "heatindex_f": 100.9,
            "dewpoint_c": 24.1,
            "dewpoint_f": 75.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.2,
            "gust_kph": 26.1,
            "uv": 8
          },
          {
            "time_epoch": 1696086000,
            "time": "2023-09-30 19:00",
            "temp_c": 31.7,
            "temp_f": 89,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 350,
            "wind_dir": "N",
            "pressure_mb": 1008,
            "pressure_in": 29.76,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 65,
            "cloud": 3,
            "feelslike_c": 37.7,
            "feelslike_f": 99.9,
            "windchill_c": 31.7,
            "windchill_f": 89,
            "heatindex_c": 37.7,
            "heatindex_f": 99.9,
            "dewpoint_c": 24.3,
            "dewpoint_f": 75.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 1
          },
          {
            "time_epoch": 1696089600,
            "time": "2023-09-30 20:00",
            "temp_c": 36,
            "temp_f": 96.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 360,
            "wind_dir": "N",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 35,
            "cloud": 0,
            "feelslike_c": 37.4,
            "feelslike_f": 99.3,
            "windchill_c": 31.6,
            "windchill_f": 88.8,
            "heatindex_c": 37.4,
            "heatindex_f": 99.3,
            "dewpoint_c": 24.1,
            "dewpoint_f": 75.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.8,
            "gust_kph": 20.5,
            "uv": 1
          },
          {
            "time_epoch": 1696093200,
            "time": "2023-09-30 21:00",
            "temp_c": 31.4,
            "temp_f": 88.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 9,
            "wind_dir": "N",
            "pressure_mb": 1009,
            "pressure_in": 29.78,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 64,
            "cloud": 3,
            "feelslike_c": 37,
            "feelslike_f": 98.6,
            "windchill_c": 31.4,
            "windchill_f": 88.6,
            "heatindex_c": 37,
            "heatindex_f": 98.6,
            "dewpoint_c": 23.9,
            "dewpoint_f": 75,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 1
          },
          {
            "time_epoch": 1696096800,
            "time": "2023-09-30 22:00",
            "temp_c": 31.4,
            "temp_f": 88.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 17,
            "wind_dir": "NNE",
            "pressure_mb": 1008,
            "pressure_in": 29.78,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 4,
            "feelslike_c": 36.8,
            "feelslike_f": 98.2,
            "windchill_c": 31.4,
            "windchill_f": 88.5,
            "heatindex_c": 36.8,
            "heatindex_f": 98.2,
            "dewpoint_c": 23.6,
            "dewpoint_f": 74.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.9,
            "uv": 1
          },
          {
            "time_epoch": 1696100400,
            "time": "2023-09-30 23:00",
            "temp_c": 31.1,
            "temp_f": 87.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 15,
            "wind_dir": "NNE",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 4,
            "feelslike_c": 35.7,
            "feelslike_f": 96.3,
            "windchill_c": 31.1,
            "windchill_f": 87.9,
            "heatindex_c": 35.7,
            "heatindex_f": 96.3,
            "dewpoint_c": 23,
            "dewpoint_f": 73.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.6,
            "gust_kph": 10.5,
            "uv": 1
          }
        ]
      }
    ]
  }
}